spring.application.name=chat-service
server.port=8082

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=health_chat_db

spring.kafka.bootstrap-servers=localhost:9092

app.kafka.topic.chat-query=chat-query-events
gemini.api.key =${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent